### Makefile.cnf --- User level configuration

## Copyright (C) 2010, 2011 Didier Verna

## Author:        Didier Verna <didier@lrde.epita.fr>
## Maintainer:    Didier Verna <didier@lrde.epita.fr>

## This file is part of Clon.

## Redistribution and use in source or binary form, with or without
## modification, are permitted provided that the following conditions are met:

## Redistributions of source code must retain the above copyright notice, this
## list of conditions and the following disclaimer.

## Redistributions in binary form must reproduce the above copyright notice,
## this list of conditions and the following disclaimer in the documentation
## and/or other materials provided with the distribution.

## Neither the names of the authors or copyright holders, nor the names of any
## contributor or organization may be used to endorse or promote products
## derived from Clon without specific prior written permission.

## CLON IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
## EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
## DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
## LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
## CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
## SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
## INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
## CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
## POSSIBILITY OF SUCH DAMAGE.


### Commentary:

## Contents management by FCM version 0.1.


### Code:

# Installation prefix. This is used for installing Clon as follows:
# - $(PREFIX)/share/common-lisp/systems/ for the system file (ASDF 1)
# - $(PREFIX)/share/doc/clon/ for the PDF documentation
# - $(PREFIX)/share/info/ for the info documentation
# If any of these are unsatisfactory, you will need to edit the Makefiles, or
# do the installation by hand.
PREFIX := /usr/local

# C compiler configuration for sb-grovel and cffi-grovel:
CC := gcc

# Lisp implementation to use (for some installation processing steps only):
# Choices are SBCL, CMUCL, CCL, ECL, CLISP and ABCL.
LISP := SBCL

# Implementation paths:
SBCL_PATH  := CC=$(CC) sbcl
CMUCL_PATH := lisp
CCL_PATH   := ccl
ECL_PATH   := ecl
# -q is needed to remove 'bye' for version.cl to work properly.
CLISP_PATH := CC=$(CC) clisp -q

# For ABCL, we need something slightly different.
ABCL_JAR   := /usr/local/src/common-lisp/abcl/dist/abcl.jar
JAVA       := java
JAVAC      := javac
JAR        := jar
SED        := sed
ABCL_PATH  := abcl


# Programs for generating the documentation:
MAKEINFO = makeinfo
TEXI2DVI = texi2dvi
DVIPS    = dvips
CONVERT  = convert


### Makefile.cnf ends here
